### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ACFaul** [cedadev/ceda-notebooks#17]
I would like to try the Baci and sentinel examples from the jupyter notebook services. However, I get a permission denied error. Which permissions do I need? Do I need to be member of a certain group workspace?

**Comment by ACFaul** [comment]
Is the data now at /datacentre/archvol5/qb152/archive/spot-23363-baci_ssv ?

**Comment by EstherConway** [comment]
Hi Anita,

Could you give me your email address so I can put this through as a proper CEDA helpdesk query

Esther

**Comment by agstephens** [comment]
Hi @ACFaul, you should be able to access the data under the standard archive path:

`/neodc/baci_ssv/data/v1.0/`

(which points to the directory: `/datacentre/archvol5/qb152/archive/spot-23363-baci_ssv`)

**Comment by ACFaul** [comment]
Email address is anfaul@bas.ac.uk
Permission gets denied when I get to 13_europe in the file path. Permissions until then are drwxr-xr-x, then they become drwxr-x---

**Comment by agstephens** [comment]
Thanks @ACFaul 

Please message support@ceda.ac.uk and tell them about the permissions issue. Please specify the full file path (including all directories) so that one of our colleagues can update the permissions. Thanks

**Comment by ACFaul** [comment]
Linked CEDA account
