### ISSUE TITLE
Where to put small caches of data?

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-notebooks#6]
Need somewhere that is public to all JASMIN users.

Could use cedaproc - but something more public would be better:
  - e.g. Small files GWS called 'training' - open to the world

**Comment by agstephens** [comment]
Or could include a mechanism to pull data to a local cache.

**Comment by agstephens** [comment]
Or maybe `cedaproc` will just work. See sub-directory "public-data".

**Comment by agstephens** [comment]
@EstherConway please see if you can access the data on `cedaproc` from a Notebook:

```
import os
os.listdir('/gws/nopw/j04/cedaproc/public-data')
```

**Comment by EstherConway** [comment]
Can access and write to directory
